# Generated by Django 5.1.5 on 2025-03-23 09:48

import config.utils.image_validaotrs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryimage',
            name='image',
            field=models.ImageField(upload_to='categories/', validators=[config.utils.image_validaotrs.validate_image_size, config.utils.image_validaotrs.validare_image_resolution]),
        ),
    ]
